### ISSUE TITLE
Bad boundary conditions directory in HEMCO_Config.rc

### ISSUE THREAD

**Issue by djvaron** [ACMG-CH4/CH4_inversion_workflow#1]
The UMI template for `HEMCO_Config.rc` has a bad target directory for the boundary condition files. Currently, HEMCO looks for the boundary conditions in:

`/home/ubuntu/ExtData/HEMCO/SAMPLE_BCs/v2019-05/CH4/`

but this doesn't exist in the AMI. As a result our GEOS-Chem simulations show XCH4 levels that are systematically far too low.

Instead, HEMCO should look here for the boundary conditions:

`/home/ubuntu/ExtData/BoundaryConditions/`

**Comment by WilliamDowns** [comment]
This should be resolved in the cloud branch (currently `add_download`).
