### ISSUE TITLE
Comments and suggestions from Daniel Jacob

### ISSUE THREAD

**Issue by djvaron** [ACMG-CH4/CH4_inversion_workflow#10]
In comments on the manuscript, Daniel made some suggestions for improving the UMI user experience.

1. Right now the user needs to think about the buffer clusters when they define their inversion domain. They also need to think about the GEOS-Chem "buffer zone" (3 pixels on all domain sides). Daniel thinks the user should only have to tell the UMI what inversion domain they're interested in, and the UMI should automate everything else -- i.e. it should add pixels around the edges for the buffer clusters and handle the buffer zone automatically.
2. Daniel also thinks the user should have to execute just one script to make everything work, end-to-end. Can we do this? For the inversion part, `run_inversion.sh` does the trick. For the spin-up and other simulations, can we make a bash script that runs everything in series, with `wait` statements between each step? Then combine this with `run_inversion.sh`? This seems a bit painful to me but maybe it's worth it. Otherwise we need to defend the multi-step UMI (run setup script -> run spin-up simulation -> run jacobian simulations -> run inversion -> visualize results)

**Comment by msulprizio** [comment]
Request 1 above has been addressed in the setup_ch4_inversion.sh script in `main`. 

Request 2 has been split off into a separate issue for easier tracking. See https://github.com/ACMG-CH4/CH4_inversion_workflow/issues/16.
