### ISSUE TITLE
Add environment files for spack environment and conda environment on aws

### ISSUE THREAD

**Issue by laestrada** [ACMG-CH4/CH4_inversion_workflow#18]
Up to this point we have added the dependencies manually on the ami, but going forward we should use environment files to track, load, and install the dependencies needed for the IMI workflow. This will help to improve our documentation of dependencies and make future updates of the ami easier/ more predictable.

**Comment by djvaron** [comment]
Need to add the following to current AMI environment:

### Conda
- conda install -c conda-forge scikit-learn
- conda install -c anaconda yaml

### Spack
- sudo apt install nco

**Comment by laestrada** [comment]
@djvaron for nco, instead of using apt install, we should use spack. Nco is already installed on the ami using spack, so no need to have multiple installs. To have it preload when a user logs in we can add `spack load nco` to ~/.bashrc.

**Comment by laestrada** [comment]
Environment files for spack and conda were created in #25. Note to create a conda environment.yml from an existing environment run the following command: `conda env export > environment.yml`

**Comment by laestrada** [comment]
Environment files for spack and conda were created in #25. Note to create a conda environment.yml from an existing environment run the following command: `conda env export > environment.yml`. Closing this issue
