### ISSUE TITLE
Permian/Cannon relics in the AMI

### ISSUE THREAD

**Issue by djvaron** [ACMG-CH4/CH4_inversion_workflow#4]
We left some relics from previous Permian/Cannon testing in the AMI. Here are two:

1. AMI comes with a `backup_files/input_data_permian/` directory. Some of the contents may not be needed, and the `permian` should not be in the standard directory name. Maybe `backup_files/input_data` instead.
2. The `sbatch` header of `run_inversion.sh` contains `huce_intel`.

**Comment by WilliamDowns** [comment]
These issues are now fixed in the cloud branch (currently `add_download`), except I have not removed any files yet from the `input_data` directory.

**Comment by djvaron** [comment]
Let's remove `unit_SF_permian.nc` from `input_data/`

**Comment by djvaron** [comment]
Also, let's remove some of the commented-out lines from the sbatch headers? All of the run scripts (I think) contain such lines referencing time limits and huce_intel.

**Comment by WilliamDowns** [comment]
Have now fixed both of these.
