### ISSUE TITLE
Can we avoid user needing to set slurm resources when submitting with sbatch?

### ISSUE THREAD

**Issue by djvaron** [ACMG-CH4/CH4_inversion_workflow#5]
Submitting simulations with `sbatch`, the user needs to know how many cores to request. Can we automate this for them? 

Otherwise we need to tell them to edit all the run scripts to use the number of cores their instance has. E.g. on c5.xlarge I had to change num cores from 8 to 4. 

At a minimum we should set the default num cores to 1 instead of 8, which is easier to explain.

Users also need to know:
- how much memory to request
- how much time to request — can this be set to infinite?

If we can't automate the memory/cores to request, then we need to provide instructions on choosing values in the Readthedocs. That would add more steps to the workflow. Avoidable?

**Comment by WilliamDowns** [comment]
This is now automated in the cloud branch (currently `add_download`).
