### ISSUE TITLE
Problem switching between EC2 instance types

### ISSUE THREAD

**Issue by djvaron** [ACMG-CH4/CH4_inversion_workflow#9]
To save money, I used a `c5.xlarge` instance to set up the UMI and run the spin-up simulation, and then switched to a `c5.9xlarge` instance to run the Jacobian simulations. 

Everything works normally when I do this, but switching back to `c5.xlarge` from `c5.9xlarge` introduces a problem with slurm.

For some reason, slurm shows the node's resources as drained, and jobs are no longer initiated after submission.

Will found a fix for this:

`sudo scontrol update nodename=ip-172-31-20-68 state=idle`

which resets the slurm state if I understand well. 

If we can't avoid this problem, then we should document it on the Readthedocs.

**Comment by WilliamDowns** [comment]
That command is now included in the Slurm initialization script that runs whenever the instance is booted.
